name: Build Releases

on:
  push:
    tags:
      - '*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - uses: actions/upload-artifact@v2
        with:
          name: template-${{runner.os}}
          path: ${{runner.workspace}}/build/bin

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        arch: [i686, x86_64]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        if: matrix.arch == 'i686'
        with:
          msystem: MINGW32
          update: true
          install: base-devel git gcc mingw-w64-${{matrix.arch}}-cmake mingw-w64-${{matrix.arch}}-gcc

      - uses: msys2/setup-msys2@v2
        if: matrix.arch == 'x86_64'
        with:
          msystem: MINGW64
          update: true
          install: base-devel git gcc mingw-w64-${{matrix.arch}}-cmake mingw-w64-${{matrix.arch}}-gcc

      - uses: actions/checkout@v2

      - name: Create Build Environment
        working-directory: ${{github.workspace}}
        run: cmake -E make_directory build

      - name: Configure CMake
        working-directory: ${{github.workspace}}
        run: cd build && cmake .. -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}
        run: cd build && cmake --build . --config $BUILD_TYPE

      - uses: actions/upload-artifact@v2
        with:
          name: template-${{runner.os}}-${{matrix.arch}}
          path: ${{github.workspace}}\build\bin